import type {
  Employee,
  LeaderboardEntry,
  Share,
  EEMVData,
  CaptionVariant,
  AdvocacyApproval,
} from "@/types/advocacy"

export const mockEmployees: Employee[] = [
  {
    id: "emp-1",
    name: "Priya Sharma",
    email: "priya.sharma@mfilterit.com",
    department: "Marketing",
    avatar: "/avatars/priya.jpg",
    socialAccounts: [
      { id: "sa-1", platform: "linkedin", handle: "priyasharma", connected: true, followers: 4520, connectedAt: "2025-08-15T10:00:00Z" },
      { id: "sa-2", platform: "twitter", handle: "@priya_sharma", connected: true, followers: 2340, connectedAt: "2025-08-15T10:05:00Z" },
      { id: "sa-3", platform: "instagram", handle: "priya.sharma.mf", connected: true, followers: 1890, connectedAt: "2025-09-01T12:00:00Z" },
    ],
    totalShares: 187,
    totalReach: 245000,
    totalClicks: 8920,
    points: 4250,
    level: 8,
    streak: 14,
    rank: 1,
    joinedAt: "2025-08-15T10:00:00Z",
  },
  {
    id: "emp-2",
    name: "Rahul Verma",
    email: "rahul.verma@mfilterit.com",
    department: "Sales",
    avatar: "/avatars/rahul.jpg",
    socialAccounts: [
      { id: "sa-4", platform: "linkedin", handle: "rahulverma_sales", connected: true, followers: 6780, connectedAt: "2025-07-20T09:00:00Z" },
      { id: "sa-5", platform: "twitter", handle: "@rahul_v_mf", connected: true, followers: 1560, connectedAt: "2025-07-20T09:10:00Z" },
    ],
    totalShares: 156,
    totalReach: 198000,
    totalClicks: 7450,
    points: 3890,
    level: 7,
    streak: 21,
    rank: 2,
    joinedAt: "2025-07-20T09:00:00Z",
  },
  {
    id: "emp-3",
    name: "Ankit Patel",
    email: "ankit.patel@mfilterit.com",
    department: "Engineering",
    avatar: "/avatars/ankit.jpg",
    socialAccounts: [
      { id: "sa-6", platform: "linkedin", handle: "ankitpatel_dev", connected: true, followers: 3240, connectedAt: "2025-09-10T11:00:00Z" },
      { id: "sa-7", platform: "twitter", handle: "@ankit_codes", connected: true, followers: 5670, connectedAt: "2025-09-10T11:05:00Z" },
    ],
    totalShares: 134,
    totalReach: 167000,
    totalClicks: 6230,
    points: 3450,
    level: 7,
    streak: 9,
    rank: 3,
    joinedAt: "2025-09-10T11:00:00Z",
  },
  {
    id: "emp-4",
    name: "Sneha Gupta",
    email: "sneha.gupta@mfilterit.com",
    department: "Marketing",
    avatar: "/avatars/sneha.jpg",
    socialAccounts: [
      { id: "sa-8", platform: "linkedin", handle: "snehagupta_mktg", connected: true, followers: 2890, connectedAt: "2025-08-01T14:00:00Z" },
      { id: "sa-9", platform: "instagram", handle: "sneha.designs", connected: true, followers: 4560, connectedAt: "2025-08-05T10:00:00Z" },
    ],
    totalShares: 123,
    totalReach: 145000,
    totalClicks: 5670,
    points: 3120,
    level: 6,
    streak: 7,
    rank: 4,
    joinedAt: "2025-08-01T14:00:00Z",
  },
  {
    id: "emp-5",
    name: "Deepak Joshi",
    email: "deepak.joshi@mfilterit.com",
    department: "Product",
    avatar: "/avatars/deepak.jpg",
    socialAccounts: [
      { id: "sa-10", platform: "linkedin", handle: "deepakjoshi_pm", connected: true, followers: 5120, connectedAt: "2025-07-01T09:00:00Z" },
      { id: "sa-11", platform: "twitter", handle: "@deepak_product", connected: true, followers: 2340, connectedAt: "2025-07-01T09:10:00Z" },
    ],
    totalShares: 112,
    totalReach: 134000,
    totalClicks: 4890,
    points: 2890,
    level: 6,
    streak: 5,
    rank: 5,
    joinedAt: "2025-07-01T09:00:00Z",
  },
  {
    id: "emp-6",
    name: "Kavita Nair",
    email: "kavita.nair@mfilterit.com",
    department: "HR",
    avatar: "/avatars/kavita.jpg",
    socialAccounts: [
      { id: "sa-12", platform: "linkedin", handle: "kavitanair_hr", connected: true, followers: 1890, connectedAt: "2025-10-01T10:00:00Z" },
    ],
    totalShares: 98,
    totalReach: 89000,
    totalClicks: 3450,
    points: 2450,
    level: 5,
    streak: 12,
    rank: 6,
    joinedAt: "2025-10-01T10:00:00Z",
  },
  {
    id: "emp-7",
    name: "Vikram Singh",
    email: "vikram.singh@mfilterit.com",
    department: "Sales",
    avatar: "/avatars/vikram.jpg",
    socialAccounts: [
      { id: "sa-13", platform: "linkedin", handle: "vikramsingh_biz", connected: true, followers: 7890, connectedAt: "2025-06-15T08:00:00Z" },
      { id: "sa-14", platform: "twitter", handle: "@vikram_sells", connected: true, followers: 1230, connectedAt: "2025-06-15T08:10:00Z" },
      { id: "sa-15", platform: "facebook", handle: "vikram.singh.mf", connected: true, followers: 3450, connectedAt: "2025-07-01T09:00:00Z" },
    ],
    totalShares: 89,
    totalReach: 112000,
    totalClicks: 4120,
    points: 2340,
    level: 5,
    streak: 3,
    rank: 7,
    joinedAt: "2025-06-15T08:00:00Z",
  },
  {
    id: "emp-8",
    name: "Meera Iyer",
    email: "meera.iyer@mfilterit.com",
    department: "Engineering",
    avatar: "/avatars/meera.jpg",
    socialAccounts: [
      { id: "sa-16", platform: "linkedin", handle: "meeraiyer_eng", connected: true, followers: 2670, connectedAt: "2025-11-01T09:00:00Z" },
      { id: "sa-17", platform: "twitter", handle: "@meera_tech", connected: true, followers: 4890, connectedAt: "2025-11-01T09:05:00Z" },
    ],
    totalShares: 78,
    totalReach: 98000,
    totalClicks: 3560,
    points: 2120,
    level: 5,
    streak: 8,
    rank: 8,
    joinedAt: "2025-11-01T09:00:00Z",
  },
  {
    id: "emp-9",
    name: "Arjun Mehta",
    email: "arjun.mehta@mfilterit.com",
    department: "Sales",
    avatar: "/avatars/arjun.jpg",
    socialAccounts: [
      { id: "sa-18", platform: "linkedin", handle: "arjunmehta_sales", connected: true, followers: 3450, connectedAt: "2025-09-15T10:00:00Z" },
    ],
    totalShares: 67,
    totalReach: 78000,
    totalClicks: 2890,
    points: 1890,
    level: 4,
    streak: 6,
    rank: 9,
    joinedAt: "2025-09-15T10:00:00Z",
  },
  {
    id: "emp-10",
    name: "Nisha Reddy",
    email: "nisha.reddy@mfilterit.com",
    department: "Product",
    avatar: "/avatars/nisha.jpg",
    socialAccounts: [
      { id: "sa-19", platform: "linkedin", handle: "nishareddy_pm", connected: true, followers: 2340, connectedAt: "2025-10-15T11:00:00Z" },
      { id: "sa-20", platform: "twitter", handle: "@nisha_product", connected: false, followers: 890, connectedAt: "2025-10-15T11:05:00Z" },
    ],
    totalShares: 56,
    totalReach: 67000,
    totalClicks: 2340,
    points: 1670,
    level: 4,
    streak: 2,
    rank: 10,
    joinedAt: "2025-10-15T11:00:00Z",
  },
  {
    id: "emp-11",
    name: "Sanjay Kumar",
    email: "sanjay.kumar@mfilterit.com",
    department: "Engineering",
    avatar: "/avatars/sanjay.jpg",
    socialAccounts: [
      { id: "sa-21", platform: "linkedin", handle: "sanjaykumar_dev", connected: true, followers: 1560, connectedAt: "2025-12-01T10:00:00Z" },
    ],
    totalShares: 45,
    totalReach: 45000,
    totalClicks: 1670,
    points: 1230,
    level: 3,
    streak: 4,
    rank: 11,
    joinedAt: "2025-12-01T10:00:00Z",
  },
  {
    id: "emp-12",
    name: "Pooja Desai",
    email: "pooja.desai@mfilterit.com",
    department: "HR",
    avatar: "/avatars/pooja.jpg",
    socialAccounts: [
      { id: "sa-22", platform: "linkedin", handle: "poojadesai_hr", connected: true, followers: 1230, connectedAt: "2026-01-05T09:00:00Z" },
      { id: "sa-23", platform: "facebook", handle: "pooja.desai.mf", connected: true, followers: 2340, connectedAt: "2026-01-05T09:10:00Z" },
    ],
    totalShares: 34,
    totalReach: 34000,
    totalClicks: 1230,
    points: 980,
    level: 3,
    streak: 1,
    rank: 12,
    joinedAt: "2026-01-05T09:00:00Z",
  },
  {
    id: "emp-13",
    name: "Rohit Agarwal",
    email: "rohit.agarwal@mfilterit.com",
    department: "Marketing",
    avatar: "/avatars/rohit.jpg",
    socialAccounts: [
      { id: "sa-24", platform: "linkedin", handle: "rohitagarwal_mktg", connected: true, followers: 1890, connectedAt: "2026-01-15T10:00:00Z" },
      { id: "sa-25", platform: "instagram", handle: "rohit.creates", connected: true, followers: 3450, connectedAt: "2026-01-15T10:05:00Z" },
    ],
    totalShares: 28,
    totalReach: 28000,
    totalClicks: 980,
    points: 780,
    level: 2,
    streak: 3,
    rank: 13,
    joinedAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "emp-14",
    name: "Aarti Bhandari",
    email: "aarti.bhandari@mfilterit.com",
    department: "Product",
    avatar: "/avatars/aarti.jpg",
    socialAccounts: [
      { id: "sa-26", platform: "linkedin", handle: "aartibhandari", connected: true, followers: 1670, connectedAt: "2026-02-01T09:00:00Z" },
    ],
    totalShares: 19,
    totalReach: 19000,
    totalClicks: 670,
    points: 560,
    level: 2,
    streak: 5,
    rank: 14,
    joinedAt: "2026-02-01T09:00:00Z",
  },
  {
    id: "emp-15",
    name: "Karan Malhotra",
    email: "karan.malhotra@mfilterit.com",
    department: "Engineering",
    avatar: "/avatars/karan.jpg",
    socialAccounts: [
      { id: "sa-27", platform: "linkedin", handle: "karanmalhotra_eng", connected: true, followers: 980, connectedAt: "2026-02-15T10:00:00Z" },
      { id: "sa-28", platform: "twitter", handle: "@karan_builds", connected: false, followers: 450, connectedAt: "2026-02-15T10:05:00Z" },
    ],
    totalShares: 12,
    totalReach: 12000,
    totalClicks: 450,
    points: 340,
    level: 1,
    streak: 2,
    rank: 15,
    joinedAt: "2026-02-15T10:00:00Z",
  },
]

export const mockLeaderboard: LeaderboardEntry[] = mockEmployees.map((emp) => ({
  rank: emp.rank,
  employeeId: emp.id,
  name: emp.name,
  avatar: emp.avatar,
  department: emp.department,
  shares: emp.totalShares,
  reach: emp.totalReach,
  clicks: emp.totalClicks,
  points: emp.points,
  streak: emp.streak,
  level: emp.level,
}))

export const mockShares: Share[] = [
  { id: "sh-1", employeeId: "emp-1", employeeName: "Priya Sharma", creativeId: "cr-22", creativeTitle: "Holi Festival Creative", platform: "instagram", caption: "Wishing everyone a colourful Holi from the mFilterIt family! May your celebrations be as vibrant as our mission to fight ad fraud.", status: "shared", sharedAt: "2026-03-10T09:30:00Z", reach: 4520, clicks: 234, impressions: 8900, pointsEarned: 35 },
  { id: "sh-2", employeeId: "emp-2", employeeName: "Rahul Verma", creativeId: "cr-10", creativeTitle: "Case Study - HDFC Bank Ad Fraud Prevention", platform: "linkedin", caption: "Proud to share how mFilterIt helped HDFC Bank save crores in ad spend through our advanced fraud detection. Real impact, real results.", status: "shared", sharedAt: "2026-03-09T14:00:00Z", reach: 6780, clicks: 456, impressions: 12300, pointsEarned: 45 },
  { id: "sh-3", employeeId: "emp-3", employeeName: "Ankit Patel", creativeId: "cr-3", creativeTitle: "Instagram Story - Product Launch Teaser", platform: "twitter", caption: "Something exciting is coming from @TickR_official! Stay tuned for a game-changer in content compliance.", status: "shared", sharedAt: "2026-03-09T11:00:00Z", reach: 5670, clicks: 345, impressions: 9800, pointsEarned: 30 },
  { id: "sh-4", employeeId: "emp-4", employeeName: "Sneha Gupta", creativeId: "cr-15", creativeTitle: "AdVault Webinar Invite Banner", platform: "linkedin", caption: "Join us for the AdVault Security Suite webinar series! Learn how to protect your digital ad investments.", status: "shared", sharedAt: "2026-03-08T16:00:00Z", reach: 2890, clicks: 178, impressions: 5600, pointsEarned: 25 },
  { id: "sh-5", employeeId: "emp-5", employeeName: "Deepak Joshi", creativeId: "cr-4", creativeTitle: "LinkedIn Thought Leadership Post", platform: "linkedin", caption: "Did you know that ad fraud costs Indian businesses over 2000 Cr annually? Here is how we are tackling this challenge head-on.", status: "shared", sharedAt: "2026-03-08T10:30:00Z", reach: 5120, clicks: 312, impressions: 9400, pointsEarned: 40 },
  { id: "sh-6", employeeId: "emp-6", employeeName: "Kavita Nair", creativeId: "cr-16", creativeTitle: "Instagram Reel - Behind the Scenes", platform: "linkedin", caption: "Life at mFilterIt - where innovation meets purpose! Proud to be part of a team that is making digital advertising safer.", status: "shared", sharedAt: "2026-03-07T12:00:00Z", reach: 1890, clicks: 89, impressions: 3400, pointsEarned: 15 },
  { id: "sh-7", employeeId: "emp-7", employeeName: "Vikram Singh", creativeId: "cr-17", creativeTitle: "Customer Testimonial - Axis Bank", platform: "linkedin", caption: "When industry leaders like Axis Bank trust mFilterIt, it validates our mission. Watch the full testimonial.", status: "shared", sharedAt: "2026-03-07T09:00:00Z", reach: 7890, clicks: 523, impressions: 14500, pointsEarned: 50 },
  { id: "sh-8", employeeId: "emp-1", employeeName: "Priya Sharma", creativeId: "cr-4", creativeTitle: "LinkedIn Thought Leadership Post", platform: "twitter", caption: "Thread: Why ad fraud detection is the most critical investment for Indian brands in 2026. Insights from @mFilterIt.", status: "shared", sharedAt: "2026-03-06T15:00:00Z", reach: 2340, clicks: 156, impressions: 4500, pointsEarned: 20 },
  { id: "sh-9", employeeId: "emp-8", employeeName: "Meera Iyer", creativeId: "cr-19", creativeTitle: "TickR Dashboard Screenshot", platform: "linkedin", caption: "Excited to show what our engineering team has been building! TickR's new dashboard brings content compliance to your fingertips.", status: "shared", sharedAt: "2026-03-06T11:30:00Z", reach: 2670, clicks: 145, impressions: 4800, pointsEarned: 20 },
  { id: "sh-10", employeeId: "emp-9", employeeName: "Arjun Mehta", creativeId: "cr-8", creativeTitle: "BrandShield Enterprise Brochure", platform: "linkedin", caption: "Looking for enterprise-grade brand protection? BrandShield has you covered. DM me for a demo!", status: "shared", sharedAt: "2026-03-05T14:00:00Z", reach: 3450, clicks: 198, impressions: 6200, pointsEarned: 25 },
  { id: "sh-11", employeeId: "emp-2", employeeName: "Rahul Verma", creativeId: "cr-6", creativeTitle: "AdVault Security Suite - Feature Overview", platform: "linkedin", caption: "Comprehensive ad verification just got smarter. Check out the AdVault Security Suite feature overview.", status: "shared", sharedAt: "2026-03-05T10:00:00Z", reach: 6780, clicks: 389, impressions: 11200, pointsEarned: 40 },
  { id: "sh-12", employeeId: "emp-3", employeeName: "Ankit Patel", creativeId: "cr-22", creativeTitle: "Holi Festival Creative", platform: "instagram", caption: "Happy Holi from Team mFilterIt! Spreading colours of trust and transparency in digital advertising.", status: "shared", sharedAt: "2026-03-10T08:00:00Z", reach: 5670, clicks: 267, impressions: 9100, pointsEarned: 30 },
  { id: "sh-13", employeeId: "emp-10", employeeName: "Nisha Reddy", creativeId: "cr-2", creativeTitle: "Q4 Performance Report Infographic", platform: "linkedin", caption: "mFilterIt Q4 results are in! Record growth in ad fraud detection accuracy. Proud to be part of this journey.", status: "shared", sharedAt: "2026-03-04T09:30:00Z", reach: 2340, clicks: 134, impressions: 4200, pointsEarned: 20 },
  { id: "sh-14", employeeId: "emp-11", employeeName: "Sanjay Kumar", creativeId: "cr-19", creativeTitle: "TickR Dashboard Screenshot", platform: "linkedin", caption: "Built with passion, designed for impact. Here is a peek at what TickR can do for your content management.", status: "shared", sharedAt: "2026-03-04T11:00:00Z", reach: 1560, clicks: 78, impressions: 2800, pointsEarned: 15 },
  { id: "sh-15", employeeId: "emp-4", employeeName: "Sneha Gupta", creativeId: "cr-22", creativeTitle: "Holi Festival Creative", platform: "instagram", caption: "Holi hai! From mFilterIt with love. May your feeds be as vibrant as this festival!", status: "shared", sharedAt: "2026-03-10T10:00:00Z", reach: 4560, clicks: 234, impressions: 7800, pointsEarned: 30 },
  { id: "sh-16", employeeId: "emp-5", employeeName: "Deepak Joshi", creativeId: "cr-13", creativeTitle: "Partner Onboarding Deck", platform: "linkedin", caption: "Exciting partnership opportunities with TickR! Reach out to learn how we can grow together.", status: "shared", sharedAt: "2026-03-03T14:30:00Z", reach: 5120, clicks: 289, impressions: 8900, pointsEarned: 35 },
  { id: "sh-17", employeeId: "emp-12", employeeName: "Pooja Desai", creativeId: "cr-16", creativeTitle: "Instagram Reel - Behind the Scenes", platform: "facebook", caption: "A day in the life at mFilterIt! Our culture of innovation and collaboration is what makes us special.", status: "shared", sharedAt: "2026-03-03T12:00:00Z", reach: 2340, clicks: 123, impressions: 4100, pointsEarned: 15 },
  { id: "sh-18", employeeId: "emp-7", employeeName: "Vikram Singh", creativeId: "cr-10", creativeTitle: "Case Study - HDFC Bank Ad Fraud Prevention", platform: "linkedin", caption: "Case study alert! How mFilterIt saved HDFC Bank significant ad spend. The numbers speak for themselves.", status: "shared", sharedAt: "2026-03-02T10:00:00Z", reach: 7890, clicks: 467, impressions: 13200, pointsEarned: 45 },
  { id: "sh-19", employeeId: "emp-13", employeeName: "Rohit Agarwal", creativeId: "cr-22", creativeTitle: "Holi Festival Creative", platform: "instagram", caption: "Rang barse! Happy Holi from all of us at mFilterIt. Here is to a colourful year ahead!", status: "shared", sharedAt: "2026-03-10T07:30:00Z", reach: 3450, clicks: 178, impressions: 5600, pointsEarned: 25 },
  { id: "sh-20", employeeId: "emp-1", employeeName: "Priya Sharma", creativeId: "cr-17", creativeTitle: "Customer Testimonial - Axis Bank", platform: "linkedin", caption: "Nothing validates our work better than client success stories. Watch how Axis Bank leverages mFilterIt.", status: "shared", sharedAt: "2026-03-01T11:00:00Z", reach: 4520, clicks: 298, impressions: 8200, pointsEarned: 35 },
  { id: "sh-21", employeeId: "emp-8", employeeName: "Meera Iyer", creativeId: "cr-3", creativeTitle: "Instagram Story - Product Launch Teaser", platform: "twitter", caption: "Big things coming from @TickR_official. As an engineer on the team, I can tell you - this will change the game.", status: "scheduled", scheduledAt: "2026-03-15T09:00:00Z", reach: 0, clicks: 0, impressions: 0, pointsEarned: 0 },
  { id: "sh-22", employeeId: "emp-2", employeeName: "Rahul Verma", creativeId: "cr-20", creativeTitle: "AdVault Case Study - Flipkart", platform: "linkedin", caption: "How Flipkart secured its digital ad ecosystem with AdVault. A must-read for every digital marketer.", status: "scheduled", scheduledAt: "2026-03-14T10:00:00Z", reach: 0, clicks: 0, impressions: 0, pointsEarned: 0 },
  { id: "sh-23", employeeId: "emp-14", employeeName: "Aarti Bhandari", creativeId: "cr-4", creativeTitle: "LinkedIn Thought Leadership Post", platform: "linkedin", caption: "The state of ad fraud in India - why every brand needs to pay attention in 2026.", status: "pending_approval", reach: 0, clicks: 0, impressions: 0, pointsEarned: 0 },
  { id: "sh-24", employeeId: "emp-15", employeeName: "Karan Malhotra", creativeId: "cr-19", creativeTitle: "TickR Dashboard Screenshot", platform: "linkedin", caption: "Proud to have contributed to building this. TickR dashboard is going to redefine content compliance.", status: "pending_approval", reach: 0, clicks: 0, impressions: 0, pointsEarned: 0 },
  { id: "sh-25", employeeId: "emp-6", employeeName: "Kavita Nair", creativeId: "cr-22", creativeTitle: "Holi Festival Creative", platform: "linkedin", caption: "Happy Holi from Team mFilterIt! Celebrating the festival of colours with our incredible team.", status: "shared", sharedAt: "2026-03-10T08:30:00Z", reach: 1890, clicks: 67, impressions: 3200, pointsEarned: 15 },
  { id: "sh-26", employeeId: "emp-9", employeeName: "Arjun Mehta", creativeId: "cr-6", creativeTitle: "AdVault Security Suite - Feature Overview", platform: "linkedin", caption: "Ad verification just levelled up. AdVault Security Suite offers comprehensive protection for your digital campaigns.", status: "shared", sharedAt: "2026-02-28T09:30:00Z", reach: 3450, clicks: 189, impressions: 5800, pointsEarned: 25 },
  { id: "sh-27", employeeId: "emp-3", employeeName: "Ankit Patel", creativeId: "cr-16", creativeTitle: "Instagram Reel - Behind the Scenes", platform: "twitter", caption: "Sneak peek into the mFilterIt engineering floor! Where ad fraud meets its match every single day.", status: "shared", sharedAt: "2026-02-28T15:00:00Z", reach: 5670, clicks: 312, impressions: 9400, pointsEarned: 30 },
  { id: "sh-28", employeeId: "emp-4", employeeName: "Sneha Gupta", creativeId: "cr-18", creativeTitle: "Email Newsletter - March 2026", platform: "linkedin", caption: "Our March newsletter is packed with insights on digital compliance trends. Subscribe to stay ahead!", status: "draft", reach: 0, clicks: 0, impressions: 0, pointsEarned: 0 },
  { id: "sh-29", employeeId: "emp-10", employeeName: "Nisha Reddy", creativeId: "cr-13", creativeTitle: "Partner Onboarding Deck", platform: "linkedin", caption: "Excited about TickR's partner programme! Great growth opportunities for businesses in the compliance space.", status: "rejected", reach: 0, clicks: 0, impressions: 0, pointsEarned: 0 },
  { id: "sh-30", employeeId: "emp-7", employeeName: "Vikram Singh", creativeId: "cr-21", creativeTitle: "Social Media Kit - BrandShield", platform: "facebook", caption: "BrandShield keeps your brand safe across every digital touchpoint. Check out our new social media kit!", status: "shared", sharedAt: "2026-02-27T10:00:00Z", reach: 3450, clicks: 178, impressions: 5800, pointsEarned: 20 },
]

export const mockEEMVData: EEMVData = {
  totalEEMV: 2450000,
  equivalentAdSpend: 1870000,
  totalReach: 1845000,
  totalImpressions: 3240000,
  avgEngagementRate: 4.2,
  monthlyTrend: [
    { month: "Apr 2025", eemv: 85000, adSpend: 65000 },
    { month: "May 2025", eemv: 92000, adSpend: 70000 },
    { month: "Jun 2025", eemv: 110000, adSpend: 84000 },
    { month: "Jul 2025", eemv: 145000, adSpend: 112000 },
    { month: "Aug 2025", eemv: 178000, adSpend: 138000 },
    { month: "Sep 2025", eemv: 195000, adSpend: 152000 },
    { month: "Oct 2025", eemv: 320000, adSpend: 248000 },
    { month: "Nov 2025", eemv: 285000, adSpend: 220000 },
    { month: "Dec 2025", eemv: 210000, adSpend: 162000 },
    { month: "Jan 2026", eemv: 245000, adSpend: 190000 },
    { month: "Feb 2026", eemv: 278000, adSpend: 215000 },
    { month: "Mar 2026", eemv: 307000, adSpend: 214000 },
  ],
}

export const mockCaptionVariants: CaptionVariant[] = [
  { id: "cv-1", text: "mFilterIt's advanced ad fraud detection has helped over 500+ brands save crores in wasted ad spend. Learn how our AI-powered platform can protect your digital investments. #AdFraud #DigitalMarketing #mFilterIt", tone: "professional", platform: "linkedin" },
  { id: "cv-2", text: "Did you know 30% of digital ad spend in India goes to fraudulent clicks? We're changing that! Check out how mFilterIt keeps your campaigns honest.", tone: "casual", platform: "linkedin" },
  { id: "cv-3", text: "We're on a MISSION to eliminate ad fraud in India and we're WINNING! 500+ brands protected and counting! Join the movement! #AdFraudFighters #mFilterIt", tone: "enthusiastic", platform: "linkedin" },
  { id: "cv-4", text: "Protecting digital ad investments with AI-powered fraud detection. @mFilterIt leads the charge against ad fraud in India. #AdTech #FraudPrevention", tone: "professional", platform: "twitter" },
  { id: "cv-5", text: "Your ads deserve real eyeballs, not bots. That's exactly what @mFilterIt delivers. No more wasted spend!", tone: "casual", platform: "twitter" },
  { id: "cv-6", text: "Ad fraud doesn't stand a chance! @mFilterIt is revolutionising digital ad verification in India! Real results, real impact! #GameChanger", tone: "enthusiastic", platform: "twitter" },
  { id: "cv-7", text: "In the ever-evolving digital landscape, ad fraud remains a significant challenge. mFilterIt provides enterprise-grade solutions that give brands complete transparency over their digital ad spend.", tone: "professional", platform: "facebook" },
  { id: "cv-8", text: "Ever wondered how much of your ad budget actually reaches real people? At mFilterIt, we make sure every rupee counts. Check us out!", tone: "casual", platform: "facebook" },
  { id: "cv-9", text: "Team mFilterIt is absolutely CRUSHING IT in the ad fraud detection space! 500+ brands, billions of impressions verified, and we're just getting started!", tone: "enthusiastic", platform: "facebook" },
]

export const mockApprovals: AdvocacyApproval[] = [
  {
    id: "apv-1",
    employeeName: "Aarti Bhandari",
    employeeAvatar: "/avatars/aarti.jpg",
    creativeTitle: "LinkedIn Thought Leadership Post",
    platform: "linkedin",
    caption: "The state of ad fraud in India - why every brand needs to pay attention in 2026.",
    submittedAt: "2026-03-11T09:00:00Z",
    status: "pending",
  },
  {
    id: "apv-2",
    employeeName: "Karan Malhotra",
    employeeAvatar: "/avatars/karan.jpg",
    creativeTitle: "TickR Dashboard Screenshot",
    platform: "linkedin",
    caption: "Proud to have contributed to building this. TickR dashboard is going to redefine content compliance.",
    submittedAt: "2026-03-11T10:30:00Z",
    status: "pending",
  },
  {
    id: "apv-3",
    employeeName: "Rohit Agarwal",
    employeeAvatar: "/avatars/rohit.jpg",
    creativeTitle: "AdVault Security Suite - Feature Overview",
    platform: "instagram",
    caption: "AdVault is here to change the game in ad verification! A must-watch for every digital marketer.",
    submittedAt: "2026-03-10T14:00:00Z",
    status: "pending",
  },
  {
    id: "apv-4",
    employeeName: "Sanjay Kumar",
    employeeAvatar: "/avatars/sanjay.jpg",
    creativeTitle: "Case Study - HDFC Bank Ad Fraud Prevention",
    platform: "linkedin",
    caption: "Incredible results from our work with HDFC Bank. This is what ad fraud prevention looks like in action!",
    submittedAt: "2026-03-10T11:00:00Z",
    status: "pending",
  },
  {
    id: "apv-5",
    employeeName: "Pooja Desai",
    employeeAvatar: "/avatars/pooja.jpg",
    creativeTitle: "Instagram Reel - Behind the Scenes",
    platform: "facebook",
    caption: "Love our team energy! Here is what a typical day looks like at mFilterIt HQ. #LifeAtmFilterIt",
    submittedAt: "2026-03-09T16:30:00Z",
    status: "pending",
  },
  {
    id: "apv-6",
    employeeName: "Vikram Singh",
    employeeAvatar: "/avatars/vikram.jpg",
    creativeTitle: "BrandShield Enterprise Brochure",
    platform: "linkedin",
    caption: "Enterprise brand protection just got a major upgrade. BrandShield is the answer to digital brand safety.",
    submittedAt: "2026-03-09T09:00:00Z",
    status: "approved",
    reviewedBy: "Priya Sharma",
    reviewNote: "Great caption, approved for sharing.",
  },
  {
    id: "apv-7",
    employeeName: "Nisha Reddy",
    employeeAvatar: "/avatars/nisha.jpg",
    creativeTitle: "Partner Onboarding Deck",
    platform: "linkedin",
    caption: "Excited about TickR's partner programme! Great growth opportunities for businesses in the compliance space.",
    submittedAt: "2026-03-08T14:00:00Z",
    status: "rejected",
    reviewedBy: "Deepak Joshi",
    reviewNote: "Partner onboarding materials are confidential. Please use the public-facing product brochure instead.",
  },
  {
    id: "apv-8",
    employeeName: "Meera Iyer",
    employeeAvatar: "/avatars/meera.jpg",
    creativeTitle: "Q4 Performance Report Infographic",
    platform: "twitter",
    caption: "Our Q4 numbers tell the story - mFilterIt is growing faster than ever! Check out the highlights.",
    submittedAt: "2026-03-08T10:00:00Z",
    status: "pending",
  },
]
