import type {
  ValidationResult,
  ApprovalItem,
  AuditEntry,
  ComplianceHealth,
} from "@/types/compliance"

export const mockValidationResults: ValidationResult[] = [
  {
    id: "vr-1",
    creativeId: "cr-12",
    creativeTitle: "Twitter Thread Graphics - Ad Fraud Stats",
    score: 62,
    status: "fail",
    violations: [
      { id: "v-1", type: "brand", severity: "major", description: "Logo placement does not meet minimum clear space requirements", rule: "BR-001: Logo Clear Space", suggestion: "Increase padding around logo to minimum 20px on all sides", location: "Top-left corner" },
      { id: "v-2", type: "content", severity: "minor", description: "Text contrast ratio below 4.5:1 on secondary text", rule: "ACC-003: Text Contrast", suggestion: "Darken text colour or lighten background for better readability" },
      { id: "v-3", type: "format", severity: "critical", description: "Image resolution below minimum 150 DPI for print use", rule: "FMT-002: Minimum Resolution", suggestion: "Re-export at 300 DPI for print-ready quality" },
    ],
    validatedAt: "2026-03-10T10:30:00Z",
    validatedBy: "AI Validator v2.1",
    ruleset: "mFilterIt Brand Guidelines v3.0",
    processingTime: 2.4,
  },
  {
    id: "vr-2",
    creativeId: "cr-22",
    creativeTitle: "Holi Festival Creative",
    score: 95,
    status: "pass",
    violations: [
      { id: "v-4", type: "format", severity: "info", description: "File size slightly above optimal for web delivery (1.6 MB vs 1 MB target)", rule: "FMT-005: File Size Optimization", suggestion: "Consider compressing to under 1 MB for faster loading" },
    ],
    validatedAt: "2026-03-05T09:00:00Z",
    validatedBy: "AI Validator v2.1",
    ruleset: "mFilterIt Brand Guidelines v3.0",
    processingTime: 1.8,
  },
  {
    id: "vr-3",
    creativeId: "cr-4",
    creativeTitle: "LinkedIn Thought Leadership Post",
    score: 100,
    status: "pass",
    violations: [],
    validatedAt: "2026-02-06T10:00:00Z",
    validatedBy: "AI Validator v2.1",
    ruleset: "mFilterIt Brand Guidelines v3.0",
    processingTime: 1.5,
  },
  {
    id: "vr-4",
    creativeId: "cr-18",
    creativeTitle: "Email Newsletter - March 2026",
    score: 74,
    status: "warning",
    violations: [
      { id: "v-5", type: "legal", severity: "major", description: "Missing unsubscribe link in email footer", rule: "LGL-001: CAN-SPAM Compliance", suggestion: "Add visible unsubscribe link in footer section" },
      { id: "v-6", type: "brand", severity: "minor", description: "Secondary font used where primary font (Poppins) is required for headings", rule: "BR-005: Typography Standards", suggestion: "Replace Open Sans headings with Poppins" },
    ],
    validatedAt: "2026-03-09T14:00:00Z",
    validatedBy: "AI Validator v2.1",
    ruleset: "mFilterIt Brand Guidelines v3.0",
    processingTime: 3.2,
  },
  {
    id: "vr-5",
    creativeId: "cr-24",
    creativeTitle: "Ad Fraud Awareness Infographic - Draft",
    score: 68,
    status: "fail",
    violations: [
      { id: "v-7", type: "content", severity: "critical", description: "Statistical claims lack source attribution", rule: "CNT-002: Data Attribution", suggestion: "Add source citations for all statistics mentioned" },
      { id: "v-8", type: "brand", severity: "major", description: "Colour used (#5500AA) not in approved brand palette", rule: "BR-003: Brand Colours", suggestion: "Replace with approved purple #530093 or #4D0C83" },
      { id: "v-9", type: "format", severity: "minor", description: "Infographic exceeds recommended scroll length for social", rule: "FMT-008: Social Format Guidelines", suggestion: "Consider splitting into a carousel of 3-4 slides" },
    ],
    validatedAt: "2026-03-11T09:30:00Z",
    validatedBy: "AI Validator v2.1",
    ruleset: "mFilterIt Brand Guidelines v3.0",
    processingTime: 2.8,
  },
  {
    id: "vr-6",
    creativeId: "cr-3",
    creativeTitle: "Instagram Story - Product Launch Teaser",
    score: 92,
    status: "pass",
    violations: [
      { id: "v-10", type: "caption", severity: "info", description: "Caption length exceeds optimal engagement range (>150 chars)", rule: "CAP-001: Caption Length", suggestion: "Shorten caption to under 150 characters for higher engagement" },
    ],
    validatedAt: "2026-01-19T08:30:00Z",
    validatedBy: "AI Validator v2.1",
    ruleset: "TickR Brand Guidelines v1.0",
    processingTime: 1.9,
  },
  {
    id: "vr-7",
    creativeId: "cr-8",
    creativeTitle: "BrandShield Enterprise Brochure",
    score: 88,
    status: "pass",
    violations: [
      { id: "v-11", type: "legal", severity: "minor", description: "Copyright year shows 2025, should be updated to 2026", rule: "LGL-003: Copyright Notice", suggestion: "Update copyright line to 2026" },
      { id: "v-12", type: "format", severity: "info", description: "PDF not tagged for accessibility (Section 508)", rule: "FMT-010: PDF Accessibility", suggestion: "Add PDF tags for screen reader compatibility" },
    ],
    validatedAt: "2026-01-08T11:00:00Z",
    validatedBy: "AI Validator v2.1",
    ruleset: "BrandShield Brand Guidelines v2.0",
    processingTime: 4.1,
  },
  {
    id: "vr-8",
    creativeId: "cr-17",
    creativeTitle: "Customer Testimonial - Axis Bank",
    score: 97,
    status: "pass",
    violations: [
      { id: "v-13", type: "legal", severity: "info", description: "Client approval documentation should be attached for testimonials", rule: "LGL-005: Testimonial Clearance", suggestion: "Attach signed client approval form" },
    ],
    validatedAt: "2026-03-02T12:00:00Z",
    validatedBy: "AI Validator v2.1",
    ruleset: "mFilterIt Brand Guidelines v3.0",
    processingTime: 5.6,
  },
  {
    id: "vr-9",
    creativeId: "cr-9",
    creativeTitle: "Facebook Ad - TickR Launch",
    score: 85,
    status: "pass",
    violations: [
      { id: "v-14", type: "content", severity: "minor", description: "Text-to-image ratio exceeds Facebook's 20% text overlay guideline", rule: "CNT-005: Platform Text Rules", suggestion: "Reduce text overlay area or move text to caption" },
    ],
    validatedAt: "2026-02-03T10:00:00Z",
    validatedBy: "AI Validator v2.1",
    ruleset: "TickR Brand Guidelines v1.0",
    processingTime: 1.6,
  },
  {
    id: "vr-10",
    creativeId: "cr-6",
    creativeTitle: "AdVault Security Suite - Feature Overview",
    score: 91,
    status: "pass",
    violations: [
      { id: "v-15", type: "format", severity: "info", description: "Video bitrate higher than needed for web streaming", rule: "FMT-012: Video Optimization", suggestion: "Re-encode at 5 Mbps for optimal web streaming" },
    ],
    validatedAt: "2026-02-12T16:30:00Z",
    validatedBy: "AI Validator v2.1",
    ruleset: "AdVault Brand Guidelines v1.5",
    processingTime: 8.2,
  },
  {
    id: "vr-11",
    creativeId: "cr-16",
    creativeTitle: "Instagram Reel - Behind the Scenes",
    score: 78,
    status: "warning",
    violations: [
      { id: "v-16", type: "code_integrity", severity: "major", description: "No tracking UTM parameters embedded in shared links", rule: "TRK-001: UTM Tagging", suggestion: "Add UTM parameters: source=instagram, medium=organic, campaign=employer_branding" },
      { id: "v-17", type: "caption", severity: "minor", description: "Caption missing required hashtags from brand guidelines", rule: "CAP-003: Required Hashtags", suggestion: "Include #mFilterIt and #AdTech in caption" },
    ],
    validatedAt: "2026-03-01T10:00:00Z",
    validatedBy: "AI Validator v2.1",
    ruleset: "mFilterIt Brand Guidelines v3.0",
    processingTime: 6.4,
  },
  {
    id: "vr-12",
    creativeId: "cr-15",
    creativeTitle: "AdVault Webinar Invite Banner",
    score: 93,
    status: "pass",
    violations: [
      { id: "v-18", type: "content", severity: "info", description: "Date format inconsistency (DD/MM vs MM/DD)", rule: "CNT-008: Date Format Standards", suggestion: "Use DD MMM YYYY format consistently (e.g., 15 Mar 2026)" },
    ],
    validatedAt: "2026-02-22T15:00:00Z",
    validatedBy: "AI Validator v2.1",
    ruleset: "AdVault Brand Guidelines v1.5",
    processingTime: 1.7,
  },
]

export const mockApprovalQueue: ApprovalItem[] = [
  {
    id: "aq-1",
    creativeId: "cr-12",
    creativeTitle: "Twitter Thread Graphics - Ad Fraud Stats",
    thumbnail: "/placeholder/creative-12.jpg",
    submittedBy: "Priya Sharma",
    submittedAt: "2026-03-10T09:00:00Z",
    status: "pending",
    complianceScore: 62,
    violations: [
      { id: "v-1", type: "brand", severity: "major", description: "Logo placement does not meet minimum clear space requirements", rule: "BR-001: Logo Clear Space", suggestion: "Increase padding around logo" },
      { id: "v-3", type: "format", severity: "critical", description: "Image resolution below minimum 150 DPI", rule: "FMT-002: Minimum Resolution", suggestion: "Re-export at 300 DPI" },
    ],
    module: "library",
  },
  {
    id: "aq-2",
    creativeId: "cr-24",
    creativeTitle: "Ad Fraud Awareness Infographic - Draft",
    thumbnail: "/placeholder/creative-24.jpg",
    submittedBy: "Priya Sharma",
    submittedAt: "2026-03-11T08:00:00Z",
    status: "pending",
    complianceScore: 68,
    violations: [
      { id: "v-7", type: "content", severity: "critical", description: "Statistical claims lack source attribution", rule: "CNT-002: Data Attribution" },
      { id: "v-8", type: "brand", severity: "major", description: "Colour not in approved brand palette", rule: "BR-003: Brand Colours" },
    ],
    module: "library",
  },
  {
    id: "aq-3",
    creativeId: "cr-18",
    creativeTitle: "Email Newsletter - March 2026",
    thumbnail: "/placeholder/creative-18.jpg",
    submittedBy: "Sneha Gupta",
    submittedAt: "2026-03-09T13:00:00Z",
    status: "pending",
    complianceScore: 74,
    violations: [
      { id: "v-5", type: "legal", severity: "major", description: "Missing unsubscribe link in email footer", rule: "LGL-001: CAN-SPAM Compliance" },
    ],
    module: "library",
  },
  {
    id: "aq-4",
    creativeId: "cr-16",
    creativeTitle: "Instagram Reel - Behind the Scenes",
    thumbnail: "/placeholder/creative-16.jpg",
    submittedBy: "Ankit Patel",
    submittedAt: "2026-02-28T11:00:00Z",
    status: "escalated",
    complianceScore: 78,
    violations: [
      { id: "v-16", type: "code_integrity", severity: "major", description: "No tracking UTM parameters embedded", rule: "TRK-001: UTM Tagging" },
    ],
    reviewedBy: "Sneha Gupta",
    reviewedAt: "2026-03-01T09:00:00Z",
    reviewNote: "Escalated to marketing lead - UTM strategy needs to be defined for employer branding content.",
    module: "advocacy",
  },
  {
    id: "aq-5",
    creativeId: "cr-22",
    creativeTitle: "Holi Festival Creative",
    thumbnail: "/placeholder/creative-22.jpg",
    submittedBy: "Ankit Patel",
    submittedAt: "2026-03-04T08:00:00Z",
    status: "approved",
    complianceScore: 95,
    violations: [],
    reviewedBy: "Priya Sharma",
    reviewedAt: "2026-03-04T10:30:00Z",
    reviewNote: "Looks great. Approved for all platforms.",
    module: "library",
  },
  {
    id: "aq-6",
    creativeId: "cr-17",
    creativeTitle: "Customer Testimonial - Axis Bank",
    thumbnail: "/placeholder/creative-17.jpg",
    submittedBy: "Rahul Verma",
    submittedAt: "2026-03-01T10:00:00Z",
    status: "approved",
    complianceScore: 97,
    violations: [],
    reviewedBy: "Deepak Joshi",
    reviewedAt: "2026-03-01T14:00:00Z",
    reviewNote: "Client approval attached. Cleared for advocacy sharing.",
    module: "advocacy",
  },
  {
    id: "aq-7",
    creativeId: "cr-9",
    creativeTitle: "Facebook Ad - TickR Launch",
    thumbnail: "/placeholder/creative-9.jpg",
    submittedBy: "Priya Sharma",
    submittedAt: "2026-02-01T10:30:00Z",
    status: "approved",
    complianceScore: 85,
    violations: [
      { id: "v-14", type: "content", severity: "minor", description: "Text-to-image ratio exceeds 20%", rule: "CNT-005: Platform Text Rules" },
    ],
    reviewedBy: "Sneha Gupta",
    reviewedAt: "2026-02-02T09:00:00Z",
    reviewNote: "Minor text issue noted but acceptable. Facebook guidelines are soft limits.",
    module: "library",
  },
  {
    id: "aq-8",
    creativeId: "cr-14",
    creativeTitle: "Republic Day Social Post",
    thumbnail: "/placeholder/creative-14.jpg",
    submittedBy: "Ankit Patel",
    submittedAt: "2026-01-21T09:00:00Z",
    status: "approved",
    complianceScore: 98,
    violations: [],
    reviewedBy: "Priya Sharma",
    reviewedAt: "2026-01-21T11:00:00Z",
    reviewNote: "Perfect. Go live immediately.",
    module: "partners",
  },
  {
    id: "aq-9",
    creativeId: "cr-11",
    creativeTitle: "Animated GIF - Sale Countdown",
    thumbnail: "/placeholder/creative-11.jpg",
    submittedBy: "Sneha Gupta",
    submittedAt: "2025-10-07T14:00:00Z",
    status: "rejected",
    complianceScore: 56,
    violations: [
      { id: "v-19", type: "brand", severity: "critical", description: "Animated logo distortion in frame 12-18", rule: "BR-002: Logo Integrity" },
      { id: "v-20", type: "content", severity: "major", description: "Pricing information outdated - shows 2024 pricing", rule: "CNT-001: Content Accuracy" },
    ],
    reviewedBy: "Deepak Joshi",
    reviewedAt: "2025-10-08T09:30:00Z",
    reviewNote: "Logo distortion is unacceptable. Fix animation frames and update pricing before resubmission.",
    module: "library",
  },
  {
    id: "aq-10",
    creativeId: "cr-5",
    creativeTitle: "Email Template - Diwali Offers",
    thumbnail: "/placeholder/creative-5.jpg",
    submittedBy: "Sneha Gupta",
    submittedAt: "2025-10-09T11:00:00Z",
    status: "approved",
    complianceScore: 89,
    violations: [
      { id: "v-21", type: "legal", severity: "minor", description: "Terms and conditions link points to staging URL", rule: "LGL-002: Link Integrity" },
    ],
    reviewedBy: "Priya Sharma",
    reviewedAt: "2025-10-10T09:00:00Z",
    reviewNote: "Approved. Update T&C link to production URL before launch.",
    module: "library",
  },
]

export const mockAuditTrail: AuditEntry[] = [
  { id: "au-1", creativeId: "cr-24", creativeTitle: "Ad Fraud Awareness Infographic - Draft", action: "upload", performedBy: "Priya Sharma", performedAt: "2026-03-08T14:00:00Z", result: "success", details: "Uploaded draft infographic for ad fraud awareness campaign", module: "library" },
  { id: "au-2", creativeId: "cr-24", creativeTitle: "Ad Fraud Awareness Infographic - Draft", action: "validate", performedBy: "AI Validator v2.1", performedAt: "2026-03-11T09:30:00Z", result: "failure", details: "Validation failed with score 68/100. 3 violations found: 1 critical, 1 major, 1 minor", module: "compliance" },
  { id: "au-3", creativeId: "cr-22", creativeTitle: "Holi Festival Creative", action: "upload", performedBy: "Ankit Patel", performedAt: "2026-03-05T08:00:00Z", result: "success", details: "Uploaded Holi festival creative for social media distribution", module: "library" },
  { id: "au-4", creativeId: "cr-22", creativeTitle: "Holi Festival Creative", action: "validate", performedBy: "AI Validator v2.1", performedAt: "2026-03-05T09:00:00Z", result: "success", details: "Validation passed with score 95/100. 1 info-level note", module: "compliance" },
  { id: "au-5", creativeId: "cr-22", creativeTitle: "Holi Festival Creative", action: "approve", performedBy: "Priya Sharma", performedAt: "2026-03-04T10:30:00Z", result: "success", details: "Approved for all platforms. No compliance concerns.", module: "compliance" },
  { id: "au-6", creativeId: "cr-22", creativeTitle: "Holi Festival Creative", action: "share", performedBy: "Priya Sharma", performedAt: "2026-03-10T09:30:00Z", result: "success", details: "Shared on Instagram via employee advocacy. Reached 4,520 users.", module: "advocacy" },
  { id: "au-7", creativeId: "cr-18", creativeTitle: "Email Newsletter - March 2026", action: "upload", performedBy: "Sneha Gupta", performedAt: "2026-03-08T09:00:00Z", result: "success", details: "Uploaded March 2026 newsletter template", module: "library" },
  { id: "au-8", creativeId: "cr-18", creativeTitle: "Email Newsletter - March 2026", action: "validate", performedBy: "AI Validator v2.1", performedAt: "2026-03-09T14:00:00Z", result: "failure", details: "Validation warning with score 74/100. Missing unsubscribe link detected.", module: "compliance" },
  { id: "au-9", creativeId: "cr-17", creativeTitle: "Customer Testimonial - Axis Bank", action: "upload", performedBy: "Rahul Verma", performedAt: "2026-03-01T11:00:00Z", result: "success", details: "Uploaded Axis Bank testimonial video (67.3 MB)", module: "library" },
  { id: "au-10", creativeId: "cr-17", creativeTitle: "Customer Testimonial - Axis Bank", action: "validate", performedBy: "AI Validator v2.1", performedAt: "2026-03-02T12:00:00Z", result: "success", details: "Validation passed with score 97/100", module: "compliance" },
  { id: "au-11", creativeId: "cr-17", creativeTitle: "Customer Testimonial - Axis Bank", action: "approve", performedBy: "Deepak Joshi", performedAt: "2026-03-01T14:00:00Z", result: "success", details: "Approved with client clearance documentation attached", module: "compliance" },
  { id: "au-12", creativeId: "cr-16", creativeTitle: "Instagram Reel - Behind the Scenes", action: "upload", performedBy: "Ankit Patel", performedAt: "2026-02-28T12:00:00Z", result: "success", details: "Uploaded employer branding reel (22.5 MB)", module: "library" },
  { id: "au-13", creativeId: "cr-16", creativeTitle: "Instagram Reel - Behind the Scenes", action: "validate", performedBy: "AI Validator v2.1", performedAt: "2026-03-01T10:00:00Z", result: "failure", details: "Validation warning with score 78/100. Missing UTM parameters.", module: "compliance" },
  { id: "au-14", creativeId: "cr-16", creativeTitle: "Instagram Reel - Behind the Scenes", action: "flag", performedBy: "Sneha Gupta", performedAt: "2026-03-01T09:00:00Z", result: "pending", details: "Escalated for UTM strategy review - employer branding content needs tracking framework", module: "compliance" },
  { id: "au-15", creativeId: "cr-12", creativeTitle: "Twitter Thread Graphics - Ad Fraud Stats", action: "upload", performedBy: "Priya Sharma", performedAt: "2026-03-10T09:00:00Z", result: "success", details: "Uploaded draft Twitter graphics for ad fraud awareness", module: "library" },
  { id: "au-16", creativeId: "cr-12", creativeTitle: "Twitter Thread Graphics - Ad Fraud Stats", action: "validate", performedBy: "AI Validator v2.1", performedAt: "2026-03-10T10:30:00Z", result: "failure", details: "Validation failed with score 62/100. Critical resolution issue found.", module: "compliance" },
  { id: "au-17", creativeId: "cr-10", creativeTitle: "Case Study - HDFC Bank Ad Fraud Prevention", action: "share", performedBy: "Rahul Verma", performedAt: "2026-03-09T14:00:00Z", result: "success", details: "Shared on LinkedIn. Reached 6,780 professionals.", module: "advocacy" },
  { id: "au-18", creativeId: "cr-4", creativeTitle: "LinkedIn Thought Leadership Post", action: "share", performedBy: "Deepak Joshi", performedAt: "2026-03-08T10:30:00Z", result: "success", details: "Shared on LinkedIn. Reached 5,120 users.", module: "advocacy" },
  { id: "au-19", creativeId: "cr-15", creativeTitle: "AdVault Webinar Invite Banner", action: "share", performedBy: "Sneha Gupta", performedAt: "2026-03-08T16:00:00Z", result: "success", details: "Shared on LinkedIn. Reached 2,890 users.", module: "advocacy" },
  { id: "au-20", creativeId: "cr-14", creativeTitle: "Republic Day Social Post", action: "expire", performedBy: "System", performedAt: "2026-02-05T00:00:00Z", result: "success", details: "Creative auto-expired as per scheduled expiry date", module: "library" },
  { id: "au-21", creativeId: "cr-5", creativeTitle: "Email Template - Diwali Offers", action: "expire", performedBy: "System", performedAt: "2025-11-30T00:00:00Z", result: "success", details: "Creative auto-expired as per scheduled expiry date", module: "library" },
  { id: "au-22", creativeId: "cr-7", creativeTitle: "WhatsApp Creative - Festival Greeting", action: "expire", performedBy: "System", performedAt: "2025-11-15T00:00:00Z", result: "success", details: "Creative auto-expired as per scheduled expiry date", module: "library" },
  { id: "au-23", creativeId: "cr-11", creativeTitle: "Animated GIF - Sale Countdown", action: "reject", performedBy: "Deepak Joshi", performedAt: "2025-10-08T09:30:00Z", result: "success", details: "Rejected due to logo distortion in animation and outdated pricing", module: "compliance" },
  { id: "au-24", creativeId: "cr-8", creativeTitle: "BrandShield Enterprise Brochure", action: "modify", performedBy: "Deepak Joshi", performedAt: "2026-01-08T10:20:00Z", result: "success", details: "Updated copyright year from 2025 to 2026 as flagged by validator", module: "library" },
  { id: "au-25", creativeId: "cr-6", creativeTitle: "AdVault Security Suite - Feature Overview", action: "approve", performedBy: "Rahul Verma", performedAt: "2026-02-12T17:00:00Z", result: "success", details: "Final approval for launch campaign distribution", module: "compliance" },
]

export const mockComplianceHealth: ComplianceHealth = {
  overallScore: 87,
  firstPassRate: 72,
  avgValidationTime: 3.2,
  totalValidations: 456,
  totalViolations: 234,
  violationsByType: [
    { type: "brand", count: 67 },
    { type: "content", count: 52 },
    { type: "format", count: 45 },
    { type: "legal", count: 34 },
    { type: "caption", count: 21 },
    { type: "code_integrity", count: 15 },
  ],
  violationsBySeverity: [
    { severity: "critical", count: 23 },
    { severity: "major", count: 78 },
    { severity: "minor", count: 89 },
    { severity: "info", count: 44 },
  ],
  monthlyTrend: [
    { month: "Apr 2025", score: 78, validations: 28 },
    { month: "May 2025", score: 79, validations: 32 },
    { month: "Jun 2025", score: 81, validations: 35 },
    { month: "Jul 2025", score: 80, validations: 38 },
    { month: "Aug 2025", score: 83, validations: 36 },
    { month: "Sep 2025", score: 82, validations: 40 },
    { month: "Oct 2025", score: 85, validations: 52 },
    { month: "Nov 2025", score: 84, validations: 45 },
    { month: "Dec 2025", score: 86, validations: 34 },
    { month: "Jan 2026", score: 87, validations: 42 },
    { month: "Feb 2026", score: 88, validations: 39 },
    { month: "Mar 2026", score: 87, validations: 35 },
  ],
}
