import type { Brand, Creative, Collection, Tag } from "@/types/content"

export const mockTags: Tag[] = [
  { id: "tag-1", name: "Diwali", category: "campaign", confidence: 0.98 },
  { id: "tag-2", name: "Product Launch", category: "campaign", confidence: 0.95 },
  { id: "tag-3", name: "Festival", category: "ai-generated", confidence: 0.92 },
  { id: "tag-4", name: "Sale", category: "ai-generated", confidence: 0.89 },
  { id: "tag-5", name: "Brand Awareness", category: "manual" },
  { id: "tag-6", name: "Performance", category: "ai-generated", confidence: 0.87 },
  { id: "tag-7", name: "Social Media", category: "manual" },
  { id: "tag-8", name: "Email", category: "manual" },
  { id: "tag-9", name: "mFilterIt", category: "brand" },
  { id: "tag-10", name: "TickR", category: "brand" },
  { id: "tag-11", name: "AdVault", category: "brand" },
  { id: "tag-12", name: "BrandShield", category: "brand" },
  { id: "tag-13", name: "Q4 Report", category: "campaign", confidence: 0.94 },
  { id: "tag-14", name: "Instagram", category: "ai-generated", confidence: 0.96 },
  { id: "tag-15", name: "Banner", category: "ai-generated", confidence: 0.91 },
  { id: "tag-16", name: "Infographic", category: "ai-generated", confidence: 0.88 },
  { id: "tag-17", name: "Testimonial", category: "manual" },
  { id: "tag-18", name: "Case Study", category: "manual" },
  { id: "tag-19", name: "Compliance", category: "ai-generated", confidence: 0.93 },
  { id: "tag-20", name: "Ad Fraud", category: "brand" },
]

export const mockBrands: Brand[] = [
  {
    id: "brand-1",
    name: "mFilterIt",
    logo: "/images/mfilterit-logo.png",
    campaigns: [
      {
        id: "camp-1",
        name: "Diwali 2025 Campaign",
        brandId: "brand-1",
        startDate: "2025-10-01",
        endDate: "2025-11-15",
        status: "completed",
        subCampaigns: [
          { id: "sub-1", name: "Diwali Social Blitz", campaignId: "camp-1" },
          { id: "sub-2", name: "Diwali Email Drip", campaignId: "camp-1" },
        ],
      },
      {
        id: "camp-2",
        name: "Q1 2026 Brand Awareness",
        brandId: "brand-1",
        startDate: "2026-01-01",
        endDate: "2026-03-31",
        status: "active",
        subCampaigns: [
          { id: "sub-3", name: "LinkedIn Thought Leadership", campaignId: "camp-2" },
        ],
      },
      {
        id: "camp-3",
        name: "Ad Fraud Awareness Month",
        brandId: "brand-1",
        startDate: "2026-04-01",
        endDate: "2026-04-30",
        status: "upcoming",
      },
    ],
  },
  {
    id: "brand-2",
    name: "TickR",
    logo: "/images/tickr-logo.png",
    campaigns: [
      {
        id: "camp-4",
        name: "TickR Product Launch 2026",
        brandId: "brand-2",
        startDate: "2026-01-15",
        endDate: "2026-04-30",
        status: "active",
        subCampaigns: [
          { id: "sub-4", name: "Launch Teaser Phase", campaignId: "camp-4" },
          { id: "sub-5", name: "Full Launch Push", campaignId: "camp-4" },
        ],
      },
      {
        id: "camp-5",
        name: "TickR Partner Enablement",
        brandId: "brand-2",
        startDate: "2025-09-01",
        endDate: "2025-12-31",
        status: "completed",
      },
    ],
  },
  {
    id: "brand-3",
    name: "AdVault",
    logo: "/images/advault-logo.png",
    campaigns: [
      {
        id: "camp-6",
        name: "AdVault Security Suite Launch",
        brandId: "brand-3",
        startDate: "2026-02-01",
        endDate: "2026-05-31",
        status: "active",
        subCampaigns: [
          { id: "sub-6", name: "Webinar Series", campaignId: "camp-6" },
          { id: "sub-7", name: "Case Study Rollout", campaignId: "camp-6" },
        ],
      },
      {
        id: "camp-7",
        name: "AdVault Year-End Review",
        brandId: "brand-3",
        startDate: "2025-11-01",
        endDate: "2025-12-31",
        status: "completed",
      },
    ],
  },
  {
    id: "brand-4",
    name: "BrandShield",
    logo: "/images/brandshield-logo.png",
    campaigns: [
      {
        id: "camp-8",
        name: "BrandShield Enterprise Push",
        brandId: "brand-4",
        startDate: "2026-01-01",
        endDate: "2026-06-30",
        status: "active",
      },
      {
        id: "camp-9",
        name: "Republic Day Special",
        brandId: "brand-4",
        startDate: "2026-01-20",
        endDate: "2026-02-05",
        status: "completed",
        subCampaigns: [
          { id: "sub-8", name: "Social Contest", campaignId: "camp-9" },
        ],
      },
    ],
  },
]

export const mockCreatives: Creative[] = [
  {
    id: "cr-1",
    title: "Diwali Sale Banner - Hero",
    description: "Main hero banner for Diwali 2025 sale campaign across web and social",
    format: "image",
    thumbnail: "/placeholder/creative-1.jpg",
    fileUrl: "/files/creative-1.png",
    fileSize: "2.4 MB",
    dimensions: "1920x1080",
    brandId: "brand-1",
    brandName: "mFilterIt",
    campaignId: "camp-1",
    campaignName: "Diwali 2025 Campaign",
    tags: [mockTags[0], mockTags[3], mockTags[14], mockTags[8]],
    platforms: ["instagram", "facebook"],
    status: "active",
    expiryDate: "2026-06-30",
    createdAt: "2025-10-05T09:30:00Z",
    updatedAt: "2025-10-08T14:15:00Z",
    downloads: 342,
    shares: 187,
    views: 2450,
    uploadedBy: "Priya Sharma",
    region: "Pan India",
  },
  {
    id: "cr-2",
    title: "Q4 Performance Report Infographic",
    description: "Quarterly performance summary for stakeholders and social sharing",
    format: "pdf",
    thumbnail: "/placeholder/creative-2.jpg",
    fileUrl: "/files/creative-2.pdf",
    fileSize: "5.1 MB",
    dimensions: "A4",
    brandId: "brand-1",
    brandName: "mFilterIt",
    campaignId: "camp-2",
    campaignName: "Q1 2026 Brand Awareness",
    tags: [mockTags[5], mockTags[12], mockTags[15], mockTags[8]],
    platforms: ["linkedin", "email"],
    status: "active",
    createdAt: "2026-01-10T11:00:00Z",
    updatedAt: "2026-01-12T16:45:00Z",
    downloads: 128,
    shares: 95,
    views: 1870,
    uploadedBy: "Rahul Verma",
  },
  {
    id: "cr-3",
    title: "Instagram Story - Product Launch Teaser",
    description: "Animated story for TickR product launch teaser phase",
    format: "video",
    thumbnail: "/placeholder/creative-3.jpg",
    fileUrl: "/files/creative-3.mp4",
    fileSize: "8.7 MB",
    dimensions: "1080x1920",
    brandId: "brand-2",
    brandName: "TickR",
    campaignId: "camp-4",
    campaignName: "TickR Product Launch 2026",
    tags: [mockTags[1], mockTags[13], mockTags[9]],
    platforms: ["instagram"],
    status: "active",
    expiryDate: "2026-04-30",
    createdAt: "2026-01-18T08:20:00Z",
    updatedAt: "2026-01-18T08:20:00Z",
    downloads: 67,
    shares: 234,
    views: 5670,
    uploadedBy: "Ankit Patel",
    region: "Pan India",
  },
  {
    id: "cr-4",
    title: "LinkedIn Thought Leadership Post",
    description: "Ad fraud awareness carousel for LinkedIn organic sharing",
    format: "image",
    thumbnail: "/placeholder/creative-4.jpg",
    fileUrl: "/files/creative-4.png",
    fileSize: "1.8 MB",
    dimensions: "1200x1200",
    brandId: "brand-1",
    brandName: "mFilterIt",
    campaignId: "camp-2",
    campaignName: "Q1 2026 Brand Awareness",
    tags: [mockTags[4], mockTags[19], mockTags[8]],
    platforms: ["linkedin"],
    status: "active",
    createdAt: "2026-02-05T10:00:00Z",
    updatedAt: "2026-02-06T09:30:00Z",
    downloads: 45,
    shares: 312,
    views: 8920,
    uploadedBy: "Priya Sharma",
  },
  {
    id: "cr-5",
    title: "Email Template - Diwali Offers",
    description: "HTML email template for Diwali promotional offers",
    format: "html",
    thumbnail: "/placeholder/creative-5.jpg",
    fileUrl: "/files/creative-5.html",
    fileSize: "340 KB",
    dimensions: "600x900",
    brandId: "brand-1",
    brandName: "mFilterIt",
    campaignId: "camp-1",
    campaignName: "Diwali 2025 Campaign",
    tags: [mockTags[0], mockTags[7], mockTags[3]],
    platforms: ["email"],
    status: "expired",
    expiryDate: "2025-11-30",
    createdAt: "2025-10-10T12:00:00Z",
    updatedAt: "2025-10-15T14:30:00Z",
    downloads: 89,
    shares: 0,
    views: 456,
    uploadedBy: "Sneha Gupta",
  },
  {
    id: "cr-6",
    title: "AdVault Security Suite - Feature Overview",
    description: "Detailed feature overview video for AdVault security product",
    format: "video",
    thumbnail: "/placeholder/creative-6.jpg",
    fileUrl: "/files/creative-6.mp4",
    fileSize: "45.2 MB",
    dimensions: "1920x1080",
    brandId: "brand-3",
    brandName: "AdVault",
    campaignId: "camp-6",
    campaignName: "AdVault Security Suite Launch",
    tags: [mockTags[1], mockTags[10], mockTags[18]],
    platforms: ["linkedin", "twitter"],
    status: "active",
    expiryDate: "2026-05-31",
    createdAt: "2026-02-10T09:00:00Z",
    updatedAt: "2026-02-12T16:00:00Z",
    downloads: 156,
    shares: 78,
    views: 3240,
    uploadedBy: "Rahul Verma",
  },
  {
    id: "cr-7",
    title: "WhatsApp Creative - Festival Greeting",
    description: "Diwali greeting creative for WhatsApp distribution",
    format: "image",
    thumbnail: "/placeholder/creative-7.jpg",
    fileUrl: "/files/creative-7.png",
    fileSize: "890 KB",
    dimensions: "1080x1080",
    brandId: "brand-1",
    brandName: "mFilterIt",
    campaignId: "camp-1",
    campaignName: "Diwali 2025 Campaign",
    tags: [mockTags[0], mockTags[2], mockTags[8]],
    platforms: ["whatsapp"],
    status: "expired",
    expiryDate: "2025-11-15",
    createdAt: "2025-10-12T07:30:00Z",
    updatedAt: "2025-10-12T07:30:00Z",
    downloads: 567,
    shares: 1230,
    views: 15400,
    uploadedBy: "Ankit Patel",
    region: "Pan India",
  },
  {
    id: "cr-8",
    title: "BrandShield Enterprise Brochure",
    description: "Digital brochure for enterprise sales enablement",
    format: "pdf",
    thumbnail: "/placeholder/creative-8.jpg",
    fileUrl: "/files/creative-8.pdf",
    fileSize: "12.3 MB",
    dimensions: "A4",
    brandId: "brand-4",
    brandName: "BrandShield",
    campaignId: "camp-8",
    campaignName: "BrandShield Enterprise Push",
    tags: [mockTags[11], mockTags[17], mockTags[4]],
    platforms: ["email", "linkedin"],
    status: "active",
    createdAt: "2026-01-05T13:00:00Z",
    updatedAt: "2026-01-08T10:20:00Z",
    downloads: 234,
    shares: 45,
    views: 890,
    uploadedBy: "Deepak Joshi",
  },
  {
    id: "cr-9",
    title: "Facebook Ad - TickR Launch",
    description: "Paid social ad creative for TickR product launch",
    format: "image",
    thumbnail: "/placeholder/creative-9.jpg",
    fileUrl: "/files/creative-9.png",
    fileSize: "1.5 MB",
    dimensions: "1200x628",
    brandId: "brand-2",
    brandName: "TickR",
    campaignId: "camp-4",
    campaignName: "TickR Product Launch 2026",
    tags: [mockTags[1], mockTags[6], mockTags[9]],
    platforms: ["facebook"],
    status: "active",
    expiryDate: "2026-04-30",
    createdAt: "2026-02-01T11:30:00Z",
    updatedAt: "2026-02-03T09:45:00Z",
    downloads: 34,
    shares: 89,
    views: 2340,
    uploadedBy: "Priya Sharma",
    region: "North India",
  },
  {
    id: "cr-10",
    title: "Case Study - HDFC Bank Ad Fraud Prevention",
    description: "Detailed case study on ad fraud detection for HDFC Bank",
    format: "pdf",
    thumbnail: "/placeholder/creative-10.jpg",
    fileUrl: "/files/creative-10.pdf",
    fileSize: "3.8 MB",
    dimensions: "A4",
    brandId: "brand-1",
    brandName: "mFilterIt",
    campaignId: "camp-2",
    campaignName: "Q1 2026 Brand Awareness",
    tags: [mockTags[17], mockTags[19], mockTags[8]],
    platforms: ["linkedin", "email"],
    status: "active",
    createdAt: "2026-02-15T10:00:00Z",
    updatedAt: "2026-02-18T15:20:00Z",
    downloads: 312,
    shares: 156,
    views: 4560,
    uploadedBy: "Rahul Verma",
  },
  {
    id: "cr-11",
    title: "Animated GIF - Sale Countdown",
    description: "Animated countdown GIF for Diwali sale social posts",
    format: "gif",
    thumbnail: "/placeholder/creative-11.jpg",
    fileUrl: "/files/creative-11.gif",
    fileSize: "4.2 MB",
    dimensions: "800x800",
    brandId: "brand-1",
    brandName: "mFilterIt",
    campaignId: "camp-1",
    campaignName: "Diwali 2025 Campaign",
    tags: [mockTags[0], mockTags[3], mockTags[6]],
    platforms: ["instagram", "twitter"],
    status: "expired",
    expiryDate: "2025-11-15",
    createdAt: "2025-10-08T15:00:00Z",
    updatedAt: "2025-10-08T15:00:00Z",
    downloads: 198,
    shares: 423,
    views: 7890,
    uploadedBy: "Sneha Gupta",
  },
  {
    id: "cr-12",
    title: "Twitter Thread Graphics - Ad Fraud Stats",
    description: "Series of graphics for Twitter thread on ad fraud statistics in India",
    format: "image",
    thumbnail: "/placeholder/creative-12.jpg",
    fileUrl: "/files/creative-12.png",
    fileSize: "2.1 MB",
    dimensions: "1200x675",
    brandId: "brand-1",
    brandName: "mFilterIt",
    campaignId: "camp-3",
    campaignName: "Ad Fraud Awareness Month",
    tags: [mockTags[19], mockTags[6], mockTags[15]],
    platforms: ["twitter"],
    status: "draft",
    createdAt: "2026-03-10T09:00:00Z",
    updatedAt: "2026-03-10T09:00:00Z",
    downloads: 0,
    shares: 0,
    views: 12,
    uploadedBy: "Priya Sharma",
  },
  {
    id: "cr-13",
    title: "Partner Onboarding Deck",
    description: "Presentation deck for new TickR partner onboarding",
    format: "pdf",
    thumbnail: "/placeholder/creative-13.jpg",
    fileUrl: "/files/creative-13.pdf",
    fileSize: "8.9 MB",
    dimensions: "16:9",
    brandId: "brand-2",
    brandName: "TickR",
    campaignId: "camp-5",
    campaignName: "TickR Partner Enablement",
    tags: [mockTags[9], mockTags[4], mockTags[17]],
    platforms: ["email"],
    status: "active",
    createdAt: "2025-09-15T14:00:00Z",
    updatedAt: "2025-11-20T11:30:00Z",
    downloads: 89,
    shares: 23,
    views: 345,
    uploadedBy: "Deepak Joshi",
  },
  {
    id: "cr-14",
    title: "Republic Day Social Post",
    description: "Republic Day themed social media creative for BrandShield",
    format: "image",
    thumbnail: "/placeholder/creative-14.jpg",
    fileUrl: "/files/creative-14.png",
    fileSize: "1.2 MB",
    dimensions: "1080x1080",
    brandId: "brand-4",
    brandName: "BrandShield",
    campaignId: "camp-9",
    campaignName: "Republic Day Special",
    tags: [mockTags[2], mockTags[6], mockTags[11]],
    platforms: ["instagram", "facebook", "twitter"],
    status: "expired",
    expiryDate: "2026-02-05",
    createdAt: "2026-01-22T08:00:00Z",
    updatedAt: "2026-01-22T08:00:00Z",
    downloads: 78,
    shares: 234,
    views: 5670,
    uploadedBy: "Ankit Patel",
    region: "Pan India",
  },
  {
    id: "cr-15",
    title: "AdVault Webinar Invite Banner",
    description: "Promotional banner for AdVault security webinar series",
    format: "image",
    thumbnail: "/placeholder/creative-15.jpg",
    fileUrl: "/files/creative-15.png",
    fileSize: "980 KB",
    dimensions: "1200x628",
    brandId: "brand-3",
    brandName: "AdVault",
    campaignId: "camp-6",
    campaignName: "AdVault Security Suite Launch",
    tags: [mockTags[10], mockTags[4], mockTags[6]],
    platforms: ["linkedin", "email"],
    status: "active",
    expiryDate: "2026-05-31",
    createdAt: "2026-02-20T10:30:00Z",
    updatedAt: "2026-02-22T14:00:00Z",
    downloads: 56,
    shares: 123,
    views: 2890,
    uploadedBy: "Sneha Gupta",
  },
  {
    id: "cr-16",
    title: "Instagram Reel - Behind the Scenes",
    description: "Behind the scenes reel from mFilterIt office for employer branding",
    format: "video",
    thumbnail: "/placeholder/creative-16.jpg",
    fileUrl: "/files/creative-16.mp4",
    fileSize: "22.5 MB",
    dimensions: "1080x1920",
    brandId: "brand-1",
    brandName: "mFilterIt",
    campaignId: "camp-2",
    campaignName: "Q1 2026 Brand Awareness",
    tags: [mockTags[13], mockTags[4], mockTags[8]],
    platforms: ["instagram"],
    status: "active",
    createdAt: "2026-02-28T12:00:00Z",
    updatedAt: "2026-03-01T09:15:00Z",
    downloads: 12,
    shares: 89,
    views: 4560,
    uploadedBy: "Ankit Patel",
  },
  {
    id: "cr-17",
    title: "Customer Testimonial - Axis Bank",
    description: "Video testimonial from Axis Bank on mFilterIt ad fraud detection",
    format: "video",
    thumbnail: "/placeholder/creative-17.jpg",
    fileUrl: "/files/creative-17.mp4",
    fileSize: "67.3 MB",
    dimensions: "1920x1080",
    brandId: "brand-1",
    brandName: "mFilterIt",
    campaignId: "camp-2",
    campaignName: "Q1 2026 Brand Awareness",
    tags: [mockTags[16], mockTags[19], mockTags[8]],
    platforms: ["linkedin", "twitter"],
    status: "active",
    createdAt: "2026-03-01T11:00:00Z",
    updatedAt: "2026-03-03T16:30:00Z",
    downloads: 78,
    shares: 198,
    views: 6780,
    uploadedBy: "Rahul Verma",
  },
  {
    id: "cr-18",
    title: "Email Newsletter - March 2026",
    description: "Monthly newsletter template for March 2026",
    format: "html",
    thumbnail: "/placeholder/creative-18.jpg",
    fileUrl: "/files/creative-18.html",
    fileSize: "420 KB",
    dimensions: "600x1200",
    brandId: "brand-1",
    brandName: "mFilterIt",
    campaignId: "camp-2",
    campaignName: "Q1 2026 Brand Awareness",
    tags: [mockTags[7], mockTags[8]],
    platforms: ["email"],
    status: "draft",
    createdAt: "2026-03-08T09:00:00Z",
    updatedAt: "2026-03-10T14:00:00Z",
    downloads: 3,
    shares: 0,
    views: 28,
    uploadedBy: "Sneha Gupta",
  },
  {
    id: "cr-19",
    title: "TickR Dashboard Screenshot",
    description: "Product screenshot showcasing TickR dashboard for marketing use",
    format: "image",
    thumbnail: "/placeholder/creative-19.jpg",
    fileUrl: "/files/creative-19.png",
    fileSize: "3.2 MB",
    dimensions: "2560x1440",
    brandId: "brand-2",
    brandName: "TickR",
    campaignId: "camp-4",
    campaignName: "TickR Product Launch 2026",
    tags: [mockTags[1], mockTags[9], mockTags[15]],
    platforms: ["linkedin", "twitter"],
    status: "active",
    createdAt: "2026-02-10T15:30:00Z",
    updatedAt: "2026-02-10T15:30:00Z",
    downloads: 45,
    shares: 67,
    views: 1230,
    uploadedBy: "Deepak Joshi",
  },
  {
    id: "cr-20",
    title: "AdVault Case Study - Flipkart",
    description: "Case study on AdVault deployment for Flipkart ad verification",
    format: "pdf",
    thumbnail: "/placeholder/creative-20.jpg",
    fileUrl: "/files/creative-20.pdf",
    fileSize: "4.5 MB",
    dimensions: "A4",
    brandId: "brand-3",
    brandName: "AdVault",
    campaignId: "camp-6",
    campaignName: "AdVault Security Suite Launch",
    tags: [mockTags[17], mockTags[10], mockTags[18]],
    platforms: ["email", "linkedin"],
    status: "active",
    createdAt: "2026-02-25T10:00:00Z",
    updatedAt: "2026-02-28T11:45:00Z",
    downloads: 189,
    shares: 67,
    views: 2340,
    uploadedBy: "Rahul Verma",
  },
  {
    id: "cr-21",
    title: "Social Media Kit - BrandShield",
    description: "Complete social media kit with templates for all platforms",
    format: "image",
    thumbnail: "/placeholder/creative-21.jpg",
    fileUrl: "/files/creative-21.zip",
    fileSize: "15.6 MB",
    dimensions: "Multiple",
    brandId: "brand-4",
    brandName: "BrandShield",
    campaignId: "camp-8",
    campaignName: "BrandShield Enterprise Push",
    tags: [mockTags[6], mockTags[11], mockTags[4]],
    platforms: ["instagram", "facebook", "linkedin", "twitter"],
    status: "active",
    createdAt: "2026-01-15T09:00:00Z",
    updatedAt: "2026-02-01T16:00:00Z",
    downloads: 234,
    shares: 156,
    views: 3450,
    uploadedBy: "Priya Sharma",
  },
  {
    id: "cr-22",
    title: "Holi Festival Creative",
    description: "Holi themed creative for brand engagement on social platforms",
    format: "image",
    thumbnail: "/placeholder/creative-22.jpg",
    fileUrl: "/files/creative-22.png",
    fileSize: "1.6 MB",
    dimensions: "1080x1080",
    brandId: "brand-1",
    brandName: "mFilterIt",
    campaignId: "camp-2",
    campaignName: "Q1 2026 Brand Awareness",
    tags: [mockTags[2], mockTags[6], mockTags[8]],
    platforms: ["instagram", "facebook", "whatsapp"],
    status: "active",
    expiryDate: "2026-03-20",
    createdAt: "2026-03-05T08:00:00Z",
    updatedAt: "2026-03-05T08:00:00Z",
    downloads: 456,
    shares: 890,
    views: 12300,
    uploadedBy: "Ankit Patel",
    region: "Pan India",
  },
  {
    id: "cr-23",
    title: "Partner Revenue Report Template",
    description: "Monthly revenue report template for partner communications",
    format: "pdf",
    thumbnail: "/placeholder/creative-23.jpg",
    fileUrl: "/files/creative-23.pdf",
    fileSize: "2.1 MB",
    dimensions: "A4",
    brandId: "brand-2",
    brandName: "TickR",
    campaignId: "camp-5",
    campaignName: "TickR Partner Enablement",
    tags: [mockTags[5], mockTags[9]],
    platforms: ["email"],
    status: "active",
    createdAt: "2025-10-20T13:00:00Z",
    updatedAt: "2026-01-05T10:30:00Z",
    downloads: 67,
    shares: 12,
    views: 234,
    uploadedBy: "Deepak Joshi",
  },
  {
    id: "cr-24",
    title: "Ad Fraud Awareness Infographic - Draft",
    description: "Draft infographic for upcoming ad fraud awareness campaign",
    format: "image",
    thumbnail: "/placeholder/creative-24.jpg",
    fileUrl: "/files/creative-24.png",
    fileSize: "3.4 MB",
    dimensions: "1200x2400",
    brandId: "brand-1",
    brandName: "mFilterIt",
    campaignId: "camp-3",
    campaignName: "Ad Fraud Awareness Month",
    tags: [mockTags[19], mockTags[15], mockTags[8]],
    platforms: ["linkedin", "twitter"],
    status: "draft",
    createdAt: "2026-03-08T14:00:00Z",
    updatedAt: "2026-03-11T09:00:00Z",
    downloads: 0,
    shares: 0,
    views: 5,
    uploadedBy: "Priya Sharma",
  },
  {
    id: "cr-25",
    title: "AdVault Year-End Summary Video",
    description: "Year-end summary video highlighting AdVault achievements in 2025",
    format: "video",
    thumbnail: "/placeholder/creative-25.jpg",
    fileUrl: "/files/creative-25.mp4",
    fileSize: "89.4 MB",
    dimensions: "1920x1080",
    brandId: "brand-3",
    brandName: "AdVault",
    campaignId: "camp-7",
    campaignName: "AdVault Year-End Review",
    tags: [mockTags[5], mockTags[10]],
    platforms: ["linkedin", "twitter"],
    status: "archived",
    createdAt: "2025-12-15T10:00:00Z",
    updatedAt: "2025-12-20T14:30:00Z",
    downloads: 234,
    shares: 89,
    views: 4560,
    uploadedBy: "Rahul Verma",
  },
]

export const mockCollections: Collection[] = [
  {
    id: "col-1",
    name: "Diwali 2025",
    description: "All creatives for Diwali 2025 campaign across brands",
    creativeIds: ["cr-1", "cr-5", "cr-7", "cr-11"],
    creativeCount: 4,
    thumbnail: "/placeholder/creative-1.jpg",
    createdAt: "2025-10-01T09:00:00Z",
    createdBy: "Priya Sharma",
  },
  {
    id: "col-2",
    name: "Product Launches",
    description: "Product launch creatives for TickR and AdVault",
    creativeIds: ["cr-3", "cr-6", "cr-9", "cr-19"],
    creativeCount: 4,
    thumbnail: "/placeholder/creative-3.jpg",
    createdAt: "2026-01-18T10:00:00Z",
    createdBy: "Ankit Patel",
  },
  {
    id: "col-3",
    name: "Social Media Kit",
    description: "Ready-to-share social media creatives across all platforms",
    creativeIds: ["cr-4", "cr-12", "cr-14", "cr-16", "cr-21", "cr-22"],
    creativeCount: 6,
    thumbnail: "/placeholder/creative-4.jpg",
    createdAt: "2026-02-01T11:00:00Z",
    createdBy: "Sneha Gupta",
  },
  {
    id: "col-4",
    name: "Email Templates",
    description: "HTML email templates and newsletter designs",
    creativeIds: ["cr-5", "cr-15", "cr-18"],
    creativeCount: 3,
    thumbnail: "/placeholder/creative-5.jpg",
    createdAt: "2025-10-10T12:00:00Z",
    createdBy: "Sneha Gupta",
  },
  {
    id: "col-5",
    name: "Quarterly Reports",
    description: "Quarterly performance reports and case studies",
    creativeIds: ["cr-2", "cr-10", "cr-20", "cr-23"],
    creativeCount: 4,
    thumbnail: "/placeholder/creative-2.jpg",
    createdAt: "2026-01-10T09:00:00Z",
    createdBy: "Rahul Verma",
  },
]
